baseURL = 'https://berglind1707.github.io/FinalProject_SocialGraphs/'
languageCode = 'en-us'
title = "Harry Potter - Final Project, Social Graphs and Interactions"
theme = "hugo-scroll"
publishDir = "docs"
